### ISSUE TITLE
REQUEST: Example for uploading artifacts, or creating release?

### ISSUE THREAD

**Issue by xxxserxxx** [sosedoff/actions#1]
Github upload-actions provides no examples of uploading multiple artifacts; all examples assume exactly one build artifact.  

You're obviously producing multiple artifacts, which would be common for Go projects.  Can you provide an example yml where you use upload-artifact to upload your built binaries?  Or upload-release-asset?  Or whatever you're doing?  It'd be a big help.

**Comment by sosedoff** [comment]
I've not used `upload-artifact` (or any other uploading action) but i dont see why you cant upload multiple files, assuming you know where those files are located. 

I have an example on how to upload prebuilt go binaries to S3, you can check out the code here: https://github.com/sosedoff/pgweb/blob/master/.github/workflows/artifacts.yml#L25-L32

**Comment by xxxserxxx** [comment]
For anyone searching for an answer to this:  I was unable to find a way to do it with only one command.  `upload-artifact` does not accept glob arguments, and will not upload a directory.  Work arounds are to either create an upload rule for every binary -- impractical if you're uploading 12+ binaries, and tedious to maintain if the binary names change regularly -- or to zip up the entire directory and upload it as one asset -- useless if you're producing binaries for, e.g., different CPU architectures or operating systems.

What I used instead was the marvinpinto/action-automatic-releases action, which **does** support globbing in a directory, and will create a draft release and upload binaries into it.  As this is what my ultimate end goal was, it worked well for me.
